"""procedural ambient soundscape. numpy -> pygame.mixer.

like the character, the sound is generated by code: layered tones whose warmth and
fullness shift with the Echo Distance and the detected state. no audio files, no
attribution footnotes, the atmosphere is computed.
"""

# Layer 3
