"""Procedural ambient soundscape (numpy synthesis -> pygame.mixer).

Like the character, the sound is generated by code: layered tones synthesized
with numpy, their warmth and fullness shifting with the Echo Distance and the
detected psychological state. No audio assets, no licensing footnotes —
the atmosphere is computed.
"""

# Implementation arrives in Layer 3.
